server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/csmark
    username: itmo_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    ru.itmo.backend.dao: INFO

app:
  cors:
    allowed-origins: http://localhost:5173
    allow-credentials: false
  reservations:
    cleanupDelayMs: 60000


